MX8 secondary boot support
foundriesio/u-boot pull request #114
Opened 2021-10-26 09:44 UTC by igoropaniuk

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

2021-10-26 13:43 UTC, igoropaniuk commented on arch/arm/mach-imx/imx8/misc.c
> +		ret = sc_misc_get_boot_container(-1, &set_id);
will replace with meaningful define instead of `-1` here

2021-10-26 13:43 UTC, igoropaniuk commented on arch/arm/mach-imx/imx8/misc.c
> +				ret = sc_misc_otp_fuse_read(-1, FUSE_IMG_SET_OFF_WORD, &fuse_val);
will provide meaningful defines instead of `-1` here

2021-10-26 13:44 UTC, igoropaniuk commented on arch/arm/mach-imx/imx8/ahab.c
> +	case 0x80:
will replace with meaningful define instead of `0x80` here

2021-10-26 20:46 UTC, ricardosalveti commented on arch/arm/mach-imx/imx8/ahab.c
> +	case 0x80:
Are we expecting this block to be extended later on? Switch/case for just one check can probably be replaced by a single if.

2021-10-26 20:48 UTC, ricardosalveti commented on arch/arm/mach-imx/imx8/misc.c
> +			if (set_id == 2) {
Maybe have a nested if !ret && set_id == 2 to reduce one indentation level?

2021-10-26 20:49 UTC, ricardosalveti commented on arch/arm/mach-imx/imx8/misc.c
> +	printf("This functionality isn't supported on iMX8 SoC");
Do we expect our common boot cmd to call enable secondary for this soc? Just thinking if that will cause this print to show up, which won't really be useful.

2021-10-27 14:34 UTC, igoropaniuk commented on arch/arm/mach-imx/imx8/misc.c
> +	printf("This functionality isn't supported on iMX8 SoC");
if won't be used, this is only for the case if user decides manually execute `imx_secondary_boot [0|1]` cmd

2021-10-28 14:57 UTC, igoropaniuk commented
@ricardosalveti @MrCry0 all comments addressed

2021-10-28 16:09 UTC, vanmaegima approved these changes

2021-10-28 17:15 UTC, MrCry0 approved these changes
LGTM

2021-10-28 17:15 UTC, MrCry0 commented on arch/arm/mach-imx/spl.c
> +	int boot_secondary = boot_mode_getprisec();
Just a suggestion:

What if rename the boot_mode_getprisec() to [is_]boot_mode_secondary() to make the function name more saying?

So that we can rewrite the spl_mmc_emmc_boot_partition():
```
int spl_mmc_emmc_boot_partition(struct mmc *mmc)
{
	return boot_mode_secondary() ? 2 : 1;
}
```
And in other places using the boot_mode_secondary() will be more clear.

2021-10-28 17:37 UTC, igoropaniuk commented on arch/arm/mach-imx/spl.c
> +	int boot_secondary = boot_mode_getprisec();
I think we can do that (renaming `boot_mode_secondary`), but in another PR, as this will touch all platforms where boot firmware updates are supported, which is out of scope of this PR

2021-10-28 18:02 UTC, MrCry0 commented on arch/arm/mach-imx/spl.c
> +	int boot_secondary = boot_mode_getprisec();
Sure, that's why I've approved this one :)

2021-10-28 22:20 UTC, mike-scott commented on arch/arm/mach-imx/spl.c
> +int spl_mmc_emmc_boot_partition(struct mmc *mmc)
This seems to conflict with the same function here (for imx8):
https://source.codeaurora.org/external/imx/uboot-imx/tree/arch/arm/mach-imx/imx8/image.c?h=imx_v2020.04_5.4.70_2.3.0#n284

2021-10-28 22:21 UTC, mike-scott commented on arch/arm/mach-imx/spl.c
> +int spl_mmc_emmc_boot_partition(struct mmc *mmc)
Oh.. maybe `CONFIG_SPL_MMC_SUPPORT` is not currently defined?

2021-10-28 22:21 UTC, mike-scott requested changes
Just the 1 question.  Overall this looks good.

2021-10-28 22:29 UTC, mike-scott commented on arch/arm/mach-imx/spl.c
> +int spl_mmc_emmc_boot_partition(struct mmc *mmc)
@igoropaniuk AH.. this does not conflict with our setup because image.c is only compiled when `CONFIG_SPL_LOAD_IMX_CONTAINER` is enabled.  And we disable here:
https://github.com/foundriesio/meta-lmp/blob/master/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx8qm-mek/lmp.cfg#L13

2021-10-28 22:31 UTC, mike-scott commented on arch/arm/mach-imx/spl.c
> +int spl_mmc_emmc_boot_partition(struct mmc *mmc)
I think we should handle the case where `CONFIG_SPL_LOAD_IMX_CONTAINER` is enabled (this will break).

2021-10-29 14:11 UTC, igoropaniuk commented on arch/arm/mach-imx/spl.c
> +int spl_mmc_emmc_boot_partition(struct mmc *mmc)
addressed

2021-10-29 14:23 UTC, mike-scott approved these changes
LGTM

2021-10-29 15:51 UTC, merged