[FIO internal] imx8: adjust address for FIT buffer
foundriesio/u-boot pull request #192
Opened 2022-11-28 12:45 UTC by igoropaniuk

Use different location for FIT image, as current one is not big enough and it overlaps with U-Boot image.

Fixes: 3c3b138ccd("[FIO internal] imx8: use different address for FIT buffer in board_spl_fit_buffer_addr()")
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

The only exception to this is in order to trigger a CI loop on Azure prior
to posting of patches.

2022-11-28 12:52 UTC, MrCry0 approved these changes
LGTM

2022-11-28 21:28 UTC, Tim-Anderson requested changes
I am currently testing this but sorry, this appears to be the address of the fdt u-boot load address I am trying 0x82000000

2022-11-28 22:42 UTC, igoropaniuk commented
@Tim-Anderson 

memory layout is:
```
* SYS_SDRAM_BASE       0x80000000      0.125MiB
* SYS_TEXT_BASE        0x80020000      2.375MiB
* kernel_addr_r        0x80280000      45.5MiB
* fdt_addr_r           0x83000000      1MiB
```

the address used for FIT image is:
```
(void *)((0x83000000 - fit_size - bl_len -
			align_len) & ~align_len);
```
it means that it will be placed somewhere in the end of `kernel_addr_r` segment and and before `fdt_addr_r` starts

2022-11-29 09:31 UTC, MrCry0 commented
@igoropaniuk @Tim-Anderson tested on apalis-imx8 and imx8mm.

The images with this commit can be found here: https://github.com/foundriesio/lmp-manifest/pull/260

2022-11-29 18:42 UTC, Tim-Anderson approved these changes
LGTM

2022-11-29 20:06 UTC, mike-scott approved these changes

2022-11-29 20:07 UTC, merged